export const sample_foods = [
  {
    //id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    //id: '2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    //id: '3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    //id: '4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    //id: '5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    //id: '6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users = [
  {
    //id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: false,
  },
  {
    //id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
];


export const sample_tables = [
  {name:"Table 1",capacity:6,isAvailable:true,location:"Inside"},
  {name:"Table 2",capacity:2,isAvailable:true,location:"Patio"},
  {name:"Table 3",capacity:7,isAvailable:true,location:"Bar"},
  {name:"Table 4",capacity:2,isAvailable:true,location:"Inside"},
  {name:"Table 5",capacity:4,isAvailable:true,location:"Inside"},
  {name:"Table 6",capacity:6,isAvailable:true,location:"Patio"},
  {name:"Table 7",capacity:4,isAvailable:true,location:"Patio"},
  {name:"Table 8",capacity:6,isAvailable:true,location:"Patio"},
  {name:"Table 9",capacity:5,isAvailable:true,location:"Inside"},
  {name:"Table 10",capacity:4,isAvailable:true,location:"Inside"},
  {name:"Table 11",capacity:5,isAvailable:true,location:"Patio"},
  {name:"Table 12",capacity:7,isAvailable:true,location:"Patio"},
  {name:"Table 13",capacity:4,isAvailable:true,location:"Inside"},
  {name:"Table 14",capacity:6,isAvailable:true,location:"Inside"},
  {name:"Table 15",capacity:4,isAvailable:true,location:"Inside"},
  {name:"Table 16",capacity:3,isAvailable:true,location:"Inside"},
  {name:"Table 17",capacity:6,isAvailable:true,location:"Inside"},
  {name:"Table 18",capacity:2,isAvailable:true,location:"Patio"},
  {name:"Table 19",capacity:7,isAvailable:true,location:"Patio"},
  {name:"Table 20",capacity:4,isAvailable:true,location:"Patio"},
  {name:"Table 21",capacity:7,isAvailable:true,location:"Bar"},
  {name:"Table 22",capacity:3,isAvailable:true,location:"Patio"},
  {name:"Table 23",capacity:5,isAvailable:true,location:"Patio"},
];

